import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import Image from "next/image";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import { ClientAPIProvider } from "@/app__/tags/[...tagIds]/GoogleMap";
import { Toaster } from "@/components/ui/sonner";
import { HubContextProvider } from "@/components/HubContext";

import { Inter } from "next/font/google";
import "./globals.css";
import { StrictMode, Suspense } from "react";
import { AuthContextProvider } from "@/components/AuthContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { PrimaryTagType } from "@/lib/tags";
import { UserMushroomMapContextProvider } from "@/components/UserMushroomMapContext";
import { Badge } from "@/components/ui/badge";
import MushroomBasket from "./MushroomBasket";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import NavMenu from "@/components/NavMenu";
import AuthButton from "./AuthButton";
import { MapContextProvider } from "@/components/MapContext";
import { StickyBreadcrumbContextProvider } from "@/components/StickyBreadcrumb";
import { UserScrolledContextProvider } from "@/components/UserScrolled";
import { ResultsLabelContextProvider } from "@/components/ResultsLabel";
import { MapMarkerContextProvider } from "@/components/MapMarkerContext";
import { UserIcon } from "lucide-react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

const API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || "";

export default function RootLayout({
  children,
  params: { hub, tags = [] },
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <TooltipProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} antialiased bg-gray-50 dark:bg-black bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-black`}
        >
          {" "}
          <StrictMode>
            <MapMarkerContextProvider>
              <ResultsLabelContextProvider>
                <UserScrolledContextProvider>
                  <StickyBreadcrumbContextProvider>
                    <MapContextProvider>
                      <UserMushroomMapContextProvider>
                        <AuthContextProvider>
                          <ThemeProvider attribute="class">
                            <ClientAPIProvider apiKey={API_KEY}>
                              <HubContextProvider
                                initialValue={tags[1] as PrimaryTagType}
                              >
                                <div className="container mx-auto max-w-[1080px] relative">
                                  <nav className="text-xs absolute z-50 w-full py-1 px-2 right-6 flex items-center justify-end">
                                    <span className="text-gray-500 text-[10px] hidden">
                                      Login
                                    </span>
                                  </nav>
                                </div>

                                {/* <Header>
                                  <Suspense>
                                    <div className="animate-fadeIn">
                                      <nav
                                        className="mx-auto flex max-w-8xl items-center justify-between p-4 lg:px-8"
                                        aria-label="Global"
                                      >
                                        <NavMenu
                                          forcePlayAnimation={false}
                                          enableLogoAnimation={true}
                                          // setForcePlayAnimation={() => null}
                                        />
                                        <AuthButton />
                                      </nav>
                                      <div className="absolute top-3 right-56 rel scale-95_ hidden md:block">
                                        <Button variant={"ghost"} asChild>
                                          <Link href="/">How It Works</Link>
                                        </Button>
                                      </div>
                                      <Separator
                                        className="absolute top-5 right-52 mr-3 mt-1 h-5 bg-muted-foreground/50 hidden md:block"
                                        orientation="vertical"
                                      />
                                      <MushroomBasket />
                                    </div>
                                  </Suspense>
                                </Header> */}
                                {children}
                                <Toaster duration={8000} />
                                <Footer />
                              </HubContextProvider>
                            </ClientAPIProvider>
                          </ThemeProvider>
                        </AuthContextProvider>
                      </UserMushroomMapContextProvider>
                    </MapContextProvider>
                  </StickyBreadcrumbContextProvider>
                </UserScrolledContextProvider>
              </ResultsLabelContextProvider>
            </MapMarkerContextProvider>
          </StrictMode>
          <SpeedInsights />
          <Analytics />
        </body>
      </html>
    </TooltipProvider>
  );
}
